/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CertPreviewRouteImport } from './routes/cert-preview'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as ApiPublicPlayRtdnRouteImport } from './routes/api/public/play-rtdn'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CertPreviewRoute = CertPreviewRouteImport.update({
  id: '/cert-preview',
  path: '/cert-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlayRtdnRoute = ApiPublicPlayRtdnRouteImport.update({
  id: '/api/public/play-rtdn',
  path: '/api/public/play-rtdn',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cert-preview': typeof CertPreviewRoute
  '/certificates': typeof CertificatesRoute
  '/community': typeof CommunityRoute
  '/courses': typeof CoursesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/roadmap': typeof RoadmapRoute
  '/verify': typeof VerifyRoute
  '/api/public/play-rtdn': typeof ApiPublicPlayRtdnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cert-preview': typeof CertPreviewRoute
  '/certificates': typeof CertificatesRoute
  '/community': typeof CommunityRoute
  '/courses': typeof CoursesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/roadmap': typeof RoadmapRoute
  '/verify': typeof VerifyRoute
  '/api/public/play-rtdn': typeof ApiPublicPlayRtdnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cert-preview': typeof CertPreviewRoute
  '/certificates': typeof CertificatesRoute
  '/community': typeof CommunityRoute
  '/courses': typeof CoursesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/roadmap': typeof RoadmapRoute
  '/verify': typeof VerifyRoute
  '/api/public/play-rtdn': typeof ApiPublicPlayRtdnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cert-preview'
    | '/certificates'
    | '/community'
    | '/courses'
    | '/leaderboard'
    | '/profile'
    | '/progress'
    | '/roadmap'
    | '/verify'
    | '/api/public/play-rtdn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/cert-preview'
    | '/certificates'
    | '/community'
    | '/courses'
    | '/leaderboard'
    | '/profile'
    | '/progress'
    | '/roadmap'
    | '/verify'
    | '/api/public/play-rtdn'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cert-preview'
    | '/certificates'
    | '/community'
    | '/courses'
    | '/leaderboard'
    | '/profile'
    | '/progress'
    | '/roadmap'
    | '/verify'
    | '/api/public/play-rtdn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CertPreviewRoute: typeof CertPreviewRoute
  CertificatesRoute: typeof CertificatesRoute
  CommunityRoute: typeof CommunityRoute
  CoursesRoute: typeof CoursesRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  RoadmapRoute: typeof RoadmapRoute
  VerifyRoute: typeof VerifyRoute
  ApiPublicPlayRtdnRoute: typeof ApiPublicPlayRtdnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cert-preview': {
      id: '/cert-preview'
      path: '/cert-preview'
      fullPath: '/cert-preview'
      preLoaderRoute: typeof CertPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/play-rtdn': {
      id: '/api/public/play-rtdn'
      path: '/api/public/play-rtdn'
      fullPath: '/api/public/play-rtdn'
      preLoaderRoute: typeof ApiPublicPlayRtdnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CertPreviewRoute: CertPreviewRoute,
  CertificatesRoute: CertificatesRoute,
  CommunityRoute: CommunityRoute,
  CoursesRoute: CoursesRoute,
  LeaderboardRoute: LeaderboardRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  RoadmapRoute: RoadmapRoute,
  VerifyRoute: VerifyRoute,
  ApiPublicPlayRtdnRoute: ApiPublicPlayRtdnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
